[package]
name = "foos"
version = "0.1.0"
authors = ["awall"]

[dependencies]
rocket = "0.4"
rocket_contrib = { version = "0.4", features = ["uuid"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.7", features = ["serde", "v4"] }
jsonwebtoken = "5.0"